# Generated by Django 4.0.5 on 2022-07-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0002_auto_20220707_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
