# Generated by Django 4.0.5 on 2022-07-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('adanger', 'High Priority'), ('bwarning', 'Medium Priority'), ('csuccess', 'Low Priority')], default='adanger', max_length=30),
        ),
    ]
